GET http://localhost:3333/showMovies

###

POST http://localhost:3333/addMovies
Content-Type: application/json

{

    "title": "De Volta para o Futuro",
    "genre": "Ficção Científica",
    "duration": 111,
    "ageRating": "12"

}

###

DELETE http://localhost:3333/deleteMovies/3

###

PATCH http://localhost:3333/changeMovies/3
Content-Type: application/json

{
    "title": "ar",
    "genre": "Audos",
    "duration": 69,
    "ageRating": "64"

}