GET http://localhost:3333/

###

POST http://localhost:3333/addMovies
Content-Type: application/json

{

    "title": "O Silêncio dos Inocentes",
    "genre": "Suspense",
    "duration": 118,
    "ageRating": "14"

}

###

DELETE http://localhost:3333/deleteMovies/3

###

PUT http://localhost:3333/changeMovies/1
Content-Type: application/json

{
    "title": "O Enigma de Outro Mundo",
    "genre": "Ficção Científica",
    "duration": 110,
    "ageRating": "14"

}